### ISSUE TITLE
Xcode 12.5: Failed to build module 'StreamingTagSwift'

### ISSUE THREAD

**Issue by Tinkeacc** [MediametrieDev/StreamingTagSwift#1]
Hey,

I updated Xcode to 12.5 (was 12.4) and now i get a swift compiler error using StreamingTagSwift 7.0.0: 

<img width="690" alt="Screenshot 2021-04-27 at 11 15 05" src="https://user-images.githubusercontent.com/11726424/116217379-de5cb180-a749-11eb-9fae-c369ae1342ee.png">

Thanks in advance

**Comment by warchimede** [comment]
Hi,

We are experiencing the same issue, also when using `StreamingTagSwift` `6.0.1`.
Do you know when a new version of `StreamingTagSwift` fixing this situation will be available ?

Thank you very much 🙏🏽

**Comment by warchimede** [comment]
[7.1.0](https://github.com/MediametrieDev/StreamingTagSwift/releases/tag/7.1.0) (3c9e809) from yesterday seems to solve this issue.

Can you please confirm @MediametrieDev ?

**Comment by Tinkeacc** [comment]
The issue seems solved since [7.1.0](https://github.com/MediametrieDev/StreamingTagSwift/releases/tag/7.1.0) ([3c9e809].

All swift interfaces was compiled using swift-compiler-version: Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55) and i didn't get the error anymore using Xcode 12.5.

Thank you @MediametrieDev 👍
