### ISSUE TITLE
7.1.1: Crash when tagging events in offline mode

### ISSUE THREAD

**Issue by toto** [MediametrieDev/StreamingTagSwift#4]
# Environment 

- iOS: 15.5
- StreamingTagSwift: 7.1.1
- Network connectivity: Offline (Airplane mode)

# Problem

When sending events to the tagger while offline the library crashes. 

Example: 

```Swift
let tagger: ReplayStreamingTagger

…

DispatchQueue.main.async {
  tagger.notifyEvent(eventState: someState, position: somePosition)
}
``` 

crashes. 

When catching this in the debugger it seems there is a `dispatch_sync` on the `sessionQueue` call used on the queue it's already on. See here:

<img width="1371" alt="Screen Shot 2022-07-12 at 12 05 45" src="https://user-images.githubusercontent.com/15453/178468869-f2b84bb5-dc1f-4360-af2f-55ae68f00143.png">

<img width="498" alt="Screen Shot 2022-07-12 at 12 21 56" src="https://user-images.githubusercontent.com/15453/178469006-d4bd25ae-9cb7-4a56-942b-470fb2eccc49.png">

This is a regression from 7.1.0 where the same call worked.

**Comment by MediametrieDev** [comment]
Hi @toto,

We fixed this issue in our future release. It's actually in internal validation, we will release it as soon as possible !
